openapi: 3.0.0
info:
  title: piii
  version: 1.0.0
servers:
  - url: https://cupu-ml-university-api.vercel.app
paths:
  /registration:
    post:
      tags:
        - default
      summary: Registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: todos
                email: todos@gmail.com
                password: 1qazxsw2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: todos@gmail.com
                password: 1qazxsw2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}